apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.serviceNamespace }}
  labels:
    app: {{ .Values.serviceName }}
    label: {{ .Values.serviceLabel }}
    chart: {{ template "kritis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ .Values.kritisInstallLabel }}: ""
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
      label: {{ .Values.serviceLabel }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        label: {{ .Values.serviceLabel }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.repository }}{{ .Values.image.image }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["--tls-cert-file=/var/tls/tls.crt",
               "--tls-key-file=/var/tls/tls.key",
               "--logtostderr"]
        ports:
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - mountPath: /var/tls
          name: tls
        - name: {{ .Values.gacSecret.name }}
          mountPath: /secret
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/{{ .Values.gacSecret.path }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tlsSecretName }}
        - name: {{ .Values.gacSecret.name }}
          secret:
            secretName: {{ .Values.gacSecret.name }}
